# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

plugins:
  - jekyll-katex

markdown: kramdown

title: 3D printed Plane
# email: your-email@example.com
description: 'I´ll describe my path to a mostly 3d-printed RC model airplane here. As logical, scientific, and well documented as possible. The regarding git with some more documentation, CAD-files, aerodynamic calculations, flight dynamics and 3d models can be found [in the repository](https://github.com/mpsdskd/3D-Print-Plane).'
#>- # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  mpsdskd
github: mpsdskd

minima:
  date_format: "%Y-%m-%d"

  # generate social links in footer
  social_links:

    github:  mpsdskd
    rss: true
    thingiverse: dskd
    
show_full: false
show_excerpts: true

#github:
#  repository_url: http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  
comment_repository: "https://github.com/3d-print-plane/3d-print-plane.github.io"
comment_repository_api: "https://api.github.com/repos/3d-print-plane/3d-print-plane.github.io"


data:
    settings:
        gh_api:
            ci: "808f174943b491ef42dc"
            cs: "c4d01857c44636e83a48624d351abb59a00f0096"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
